<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Stagem Team
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_GoogleRetag
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php
/**
 * Google Targeting
 *
 * @var Stagem_GoogleRetag_Block_Js_Targeting $this
 */
?>

<script type="text/javascript">
//<![CDATA[
window['GoogleAnalyticsObject'] = 'ga';
window['ga'] = window['ga'] || function() {
  (window['ga'].q = window['ga'].q || []).push(arguments)
};

var Stagem = Stagem || {};
Stagem.GoogleRetag = {};
Stagem.GoogleRetag.targets = <?= json_encode($this->getTargets()) ?>;
Stagem.GoogleRetag.fullActionName = '<?= Mage::app()->getFrontController()->getAction()->getFullActionName() ?>';
</script>

<?php return ?>

document.observe("dom:loaded", function () {
<?php $targets = $this->getTargets(); ?>
<?php foreach ($targets as $target) : ?>
  <?php $fullActions = explode(',', $target['full_action_name']); ?>
  <?php foreach ($fullActions as $action) : ?>
    <?php if (!$this->matchFullAction($action)) : ?>
      <?php continue; ?>
    <?php endif; ?>
    jQuery('<?= $target['selector'] ?>').on('<?= $target['event'] ?>', function () {
      var elm = jQuery(this);
      var form = elm.closest('form');
      if (form.length && form.has('[class^=required-], [class^=validate-]')) {

      }
      <?= $target['code'] ?>;
      console.log("Run target: <?= $target['code'] ?>");
    });
  <?php endforeach; ?>
<?php endforeach; ?>
});
//]]>
</script>
