<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Stagem Team
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_GoogleRetag
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php
/**
 * Google Targeting
 *
 * @var Stagem_GoogleRetag_Block_Js_Targeting $this
 */
?>

<script type="text/javascript">
//<![CDATA[
Stagem.GoogleRetag.path     = '<?php echo Mage::helper('core')->jsQuoteEscape($this->getPath()) ?>';
Mage.Cookies.domain   = '<?php echo Mage::helper('core')->jsQuoteEscape($this->getDomain()) ?>';
//]]>

//<![CDATA[
document.observe("dom:loaded", function () {
<?php $targets = $this->getTargets(); ?>
<?php foreach ($targets as $target) : ?>
  <?php if (!$this->matchFullAction($target['action'])) : ?>
    <?php continue; ?>
  <?php endif; ?>
  jQuery(<?= $target['selector'] ?>).on('click', function() {
      <?= $target['selector'] ?>
  });
<?php endforeach; ?>
});
//]]>
</script>
